### PR TITLE
tests: unit tests for error classes - GlueError, Failure and so on

### PR DESCRIPTION
**Pull request by happz**

### CODE REVIEW

**Review by thrix — COMMENTED** [review]
LGTM, did not find anything bad with the code. Manual execution fine.

**Review by thrix — APPROVED** [review]
Forgot to approve previously

**Review by optak — APPROVED** [review]

**Comment by happz** [comment]
I rebased the patch to current master, to let it get checked by Codecov I made mandatory for all patches, which obviously invalidated reviews **again**. Therefore, be so kind and give it your approval again, and sorry for these shenanigans, it's just this time.

@thrix @optak @mkluson @happz

**Review by mkluson — APPROVED** [review]

**Review by mkluson — APPROVED** [review]

**Review by thrix — APPROVED** [review]
LGTM

**Pull request merged**
