### PR TITLE
Report the original failure when the destroy chain yields another one

### PR DESCRIPTION
**Pull request by happz**

### CODE REVIEW

**Review by optak — DISMISSED** [review]
LGTM

**Review by ukulekek — DISMISSED** [review]

**Comment by thrix** [comment]
@happz note that travis is not happy about the update ...

**Comment by thrix** [comment]
@happz note that travis is not happy about the update ...

**Comment by happz** [comment]
Oops, I didn't notice, will fix.

**Comment by happz** [comment]
Oops, I didn't notice, will fix.

**Review by thrix — APPROVED** [review]
LGTM, learned about `@overload` decorator ...

**Pull request merged**
