### PR TITLE
logging: add new-lines to separate exception report from the error message

### PR DESCRIPTION
**Pull request by happz**

### CODE REVIEW

**Comment by happz** [comment]
@thrix @mkluson @optak - Please, give it a quick review - it's not urgent, yet it's so trivial (and so bothering me!) that I'd like to include it in the next release, which I was hoping to get out today.

**Review by mkluson — APPROVED** [review]

**Review by thrix — COMMENTED** [review]
LGTM

**Review by thrix — APPROVED** [review]
LGTM

**Comment by happz** [comment]
Overruling codecov/patch - it is a trivial change.

**Pull request merged**
