### PR TITLE
tests: unit tests of gluetool.glue.PipelineStep

### PR DESCRIPTION
**Pull request by happz**

### CODE REVIEW

**Review by thrix — COMMENTED** [review]
LGTM, seems to be working fine

**Review by thrix — APPROVED** [review]
Forgot to approve previously

**Review by optak — DISMISSED** [review]

**Comment by happz** [comment]
I rebased the patch to current master, to let it get checked by Codecov I made mandatory for all patches, which obviously invalidated reviews **again**. Therefore, be so kind and give it your approval again, and sorry for these shenanigans, it's just this time.

@thrix @optak @mkluson @happz

**Review by mkluson — DISMISSED** [review]

**Review by thrix — DISMISSED** [review]
LGTM

**Review by thrix — APPROVED** [review]
LGTM

**Review by optak — APPROVED** [review]

**Review by mkluson — APPROVED** [review]

**Comment by happz** [comment]
Thank you, guys, and again sorry for the mess.

**Pull request merged**
