### PR TITLE
log: Allow debugging early via env var

### PR DESCRIPTION
**Pull request by thrix**
By setting the GLUETOOL_DEBUG variable to any value.

Changelog: gluetool now supports early debugging by setting the GLUETOOL_DEBUG environment variable.

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

### CODE REVIEW

**Comment by thrix** [comment]
Meh, need to fix the commit message typo

**Review by happz — APPROVED** [review]
LGTM

**Review by mkluson — APPROVED** [review]

**Review by optak — APPROVED** [review]

**Comment by thrix** [comment]
@happz LGTM, but no approve? :)

**Comment by happz** [comment]
I rebased the patch to current master, to let it get checked by Codecov I made mandatory for all patches, which obviously invalidated reviews **again**. Therefore, be so kind and give it your approval again, and sorry for these shenanigans, it's just this time.

@thrix @optak @mkluson @happz

**Review by happz — APPROVED** [review]

**Review by mkluson — APPROVED** [review]
LGTM

**Pull request merged**
